{{- if .Values.matomo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo-mysqld-exporter
  labels:
    app: matomo
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: mysqld-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo
      release: {{ .Release.Name }}
      component: mysqld-exporter
  template:
    metadata:
      annotations:
        checksum/matomo-mysqld-secret: {{ include (print $.Template.BasePath "/matomo/mysqld-exporter/secret.yaml") . | sha256sum }}
        # Scrape for mysql metrics
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
      labels:
        app: matomo
        release: {{ .Release.Name }}
        component: mysqld-exporter
    spec:
      automountServiceAccountToken: false
      nodeSelector: {{ .Values.matomo.nodeSelector | toJson }}
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      containers:
      - name: prometheus-mysqld-exporter
        image: prom/mysqld-exporter:v0.11.0
        env:
          - name: DATA_SOURCE_NAME
            valueFrom:
              secretKeyRef:
                name: matomo-mysqld-secret
                key: prometheus.mysqld.data-source
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command:
          - /cloud_sql_proxy
          - -instances={{ .Values.matomo.db.instanceName }}=tcp:3306
          - -credential_file=/secrets/cloudsql/credentials.json
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
{{- end }}
