# Copy of pod.yaml without file extension for test
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  initContainers:
  - name: tc-init
    image: minrk/tc-init:0.0.1
    env:
    - name: UPLOAD_RATE
      value: 1mbit
    # - name: DOWNLOAD_RATE
    #   value: 4mbit
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
  containers:
  - name: main
    image: jupyter/minimal-notebook:e89b2fe9974b
