{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
{{ $root := . }}
kind: Ingress
metadata:
  name: redirector
  labels:
    app: redirector
  annotations:
    {{- range $key, $value := .Values.redirector.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{ range $redirect := .Values.redirector.redirects }}
    - host: {{ $redirect.host.from | quote }}
      http:
        paths:
          - path: /
            {{- if $root.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: redirector
                port:
                  number: 80
            {{- else }}
            backend:
              serviceName: redirector
              servicePort: 80
            {{- end }}
    {{ end }}
  tls:
    - secretName: {{ .Values.redirector.ingress.tls.secretName }}
      hosts:
      {{- range $redirect := .Values.redirector.redirects }}
      - {{ $redirect.host.from }}
      {{- end }}
