# minimal content for fields required in secret config
# for use when linting/testing PRs prior to merge
binderhub:
  networkPolicy:
    egress:
      bannedIps:
        - "1.1.1.1/32"
    ingress:
      bannedIps:
        - "1.1.1.1/32"
matomo:
  db:
    serviceAccountKey: "abc123"

analyticsPublisher:
  serviceAccountKey: "abc123"
