# Ingress that serves whitelisted static images only
# This allows end users to include our badges without us
# accidentally tracking all the people who see the badges.
# https://github.com/jupyterhub/binderhub/issues/379 has more info.
#
# This is a separate path-whitelisted ingress rather than just
# a domain alias to prevent possible reflection attacks.
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
{{ $root := . }}
kind: Ingress
metadata:
  name: static
  labels:
    app: static
    component: frontend
  annotations:
    {{- range $key, $value := .Values.static.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{ range $host := .Values.static.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          {{ range $path := $root.Values.static.paths }}
          - path: {{ $path }}
            {{- if $root.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: binder
                port:
                  number: 80
            {{- else }}
            backend:
              serviceName: binder
              servicePort: 80
            {{- end }}
          {{ end }}
    {{ end }}
  tls:
    - secretName: {{ .Values.static.ingress.tls.secretName }}
      hosts:
      {{ range $host := .Values.static.ingress.hosts }}
      - {{ $host }}
      {{- end }}
