dependencies:
 # Ingress-Nginx to route network traffic according to Ingress resources using
 # this controller from within k8s.
 # Source code:   https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx
 # App changelog: https://github.com/kubernetes/ingress-nginx/blob/master/Changelog.md
 #
 # NOTE: chart v2.13.0 maps to app v0.35.0  - 2020-09-01
 #       chart v3 upgrade require k8s 1.16
 #       chart v3.3.0 maps to app v0.35.0
 #       chart v3.12.0 requires Helm 3
 - name: ingress-nginx
   version: 2.13.0
   repository: https://kubernetes.github.io/ingress-nginx

 # Prometheus for collection of metrics.
 # Source code:   https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
 # App changelog: https://github.com/prometheus/prometheus/blob/master/CHANGELOG.md
 #
 # NOTE: chart v11.0.2 maps to app v2.16.0   - 2020-07-10
 #       chart v11.16.9 maps to app v2.21.0
 #       chart v12 requires Helm 3
 - name: prometheus
   version: 11.0.2
   repository: https://charts.helm.sh/stable

 # Grafana for dashboarding of metrics.
 # Source code:   https://github.com/grafana/helm-charts/tree/main/charts/grafana
 # App changelog: https://github.com/grafana/grafana/blob/master/CHANGELOG.md
 #
 # NOTE: chart v3.10.1 maps to app v6.4.2   - 2019-11-22
 #       chart v5 upgrade requires helm2 --force
 #       chart v5.0.26 maps to app v6.7.3
 #       chart v5.1.2 maps to app v7.0.1
 #       chart v6 requires Helm 3
 - name: grafana
   version: 3.10.1
   repository: https://charts.helm.sh/stable

 - name: binderhub
   version: 0.2.0-n451.h6a2b398
   repository: https://jupyterhub.github.io/helm-chart
