dependencies:
 - name: ingress-nginx
   version: 2.13.0
   repository: https://kubernetes.github.io/ingress-nginx
 - name: prometheus
   version: 11.0.2
   repository: https://charts.helm.sh/stable
 - name: grafana
   version: 3.10.1
   repository: https://charts.helm.sh/stable
 - name: binderhub
   version: 0.2.0-n439.h2b921f1
   repository: https://jupyterhub.github.io/helm-chart
